// <auto-generated />
using Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Contexto.Migrations
{
    [DbContext(typeof(EmisoraDbContext))]
    [Migration("20180410141238_crearTablas")]
    partial class crearTablas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelos.Grabacion", b =>
                {
                    b.Property<int>("GrabacionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link");

                    b.HasKey("GrabacionId");

                    b.ToTable("Grabacion");
                });

            modelBuilder.Entity("Modelos.Transmision", b =>
                {
                    b.Property<int>("TransmisionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link");

                    b.HasKey("TransmisionId");

                    b.ToTable("Transmision");
                });
#pragma warning restore 612, 618
        }
    }
}
